# Cluster Training Configuration for CRC Molecular Subtype Classification
# Optimized for multi-GPU/multi-node distributed training

# Experiment settings
experiment:
  name: "crc_molecular_epoc_v2"
  project: "crc_molecular_subtypes"
  tags: ["epoc", "distributed", "production"]
  description: "Multi-scale molecular subtype classification on EPOC cohort"

# Data configuration
data:
  train_manifest: "data/processed/manifests/train_manifest.json"
  val_manifest: "data/processed/manifests/val_manifest.json"
  test_manifest: "data/processed/manifests/test_manifest.json"
  
  # Multi-scale patch configuration
  patch_sizes:
    level_0: 256  # 20x magnification
    level_1: 512  # 10x magnification
    level_2: 1024 # 5x magnification
  
  # Data loading
  batch_size: 32  # Per GPU
  num_workers: 8
  pin_memory: true
  prefetch_factor: 2
  
  # Augmentation settings
  train_transforms:
    random_flip: true
    random_rotation: 90
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    elastic_transform:
      alpha: 120
      sigma: 9
      p: 0.5
    random_blur:
      kernel_size: 5
      p: 0.3
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  
  val_transforms:
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Model configuration
model:
  backbone: "efficientnet_b3"
  pretrained_path: "pretrained/histossl_efficientnet_b3.pth"
  feature_dim: 512
  
  # Aggregation settings
  local_aggregation: "gated_attention"
  global_aggregation: "transformer"
  num_heads: 8
  depth: 4
  
  # Pathway indices
  pathway_indices:
    canonical: 0
    immune: 1
    stromal: 2
  
  # Uncertainty estimation
  evidence_dim: 512
  uncertainty_weight: 0.1

# Training configuration
training:
  epochs: 100
  optimizer: "adamw"
  
  # Learning rates
  backbone_lr: 1e-5
  head_lr: 1e-3
  min_lr: 1e-7
  
  # Optimizer settings
  weight_decay: 0.01
  momentum: 0.9  # For SGD
  
  # Scheduler
  scheduler: "cosine"
  warmup_epochs: 5
  
  # Loss weights
  ce_weight: 1.0
  uncertainty_weight: 0.1
  pathway_weight: 0.2
  kl_weight: 0.01
  
  # Training strategy
  accumulation_steps: 4
  gradient_clip: 1.0
  use_amp: true  # Automatic mixed precision
  
  # Validation
  val_frequency: 1
  early_stopping_patience: 15
  
  # Checkpointing
  checkpoint_frequency: 5
  checkpoint_dir: "/scratch/checkpoints/crc_molecular"
  keep_checkpoints: 5

# Distributed training
distributed:
  backend: "nccl"
  init_method: "env://"
  find_unused_parameters: false
  
  # Multi-node settings
  nodes: 4
  gpus_per_node: 8
  master_addr: "node001"
  master_port: 29500

# Cluster resources
resources:
  partition: "gpu"
  time_limit: "48:00:00"
  memory: "512GB"
  cpus_per_task: 32
  
  # SLURM specific
  account: "medical_ai"
  qos: "normal"
  
  # Module loads
  modules:
    - "cuda/11.8"
    - "python/3.11"
    - "openmpi/4.1.4"

# Monitoring
monitoring:
  use_wandb: true
  wandb_project: "crc_molecular_production"
  wandb_entity: "medical_ai_team"
  
  log_frequency: 50
  tensorboard_dir: "/scratch/tensorboard/crc_molecular"
  
  # Metrics to track
  metrics:
    - "accuracy"
    - "f1_per_class"
    - "auroc"
    - "uncertainty_quality"
    - "pathway_scores"
    - "survival_concordance"

# Clinical validation
clinical:
  # Cross-validation folds
  cv_folds: 5
  stratify_by: ["molecular_subtype", "institution", "stage"]
  
  # Clinical metrics
  compute_survival_analysis: true
  compute_decision_curves: true
  compute_calibration: true
  
  # Subgroup analysis
  subgroups:
    - "msi_status"
    - "braf_mutation"
    - "age_group"
    - "tumor_location"

# Production settings
production:
  model_registry: "s3://medical-ai-models/crc_molecular/"
  
  # Inference settings
  inference_batch_size: 64
  max_patches_per_wsi: 10000
  confidence_threshold: 0.8
  
  # Clinical integration
  generate_heatmaps: true
  generate_reports: true
  audit_logging: true
  
  # Performance requirements
  max_processing_time: 300  # seconds per WSI
  min_accuracy: 0.85
  
# Data paths
paths:
  raw_data: "/data/epoc/wsi/"
  processed_data: "/data/epoc/processed/"
  cache_dir: "/scratch/cache/crc_molecular/"
  results_dir: "/results/crc_molecular/"
  
# Preprocessing pipeline
preprocessing:
  num_workers: 32
  
  # Quality control
  blur_threshold: 100.0
  tissue_threshold: 0.5
  artifact_detection: true
  
  # Stain normalization
  stain_norm_method: "macenko"
  reference_image: "data/reference_stain.png"
  
  # Patch extraction
  overlap: 0.25
  save_format: "hdf5"
  compression: "gzip" 